### ISSUE TITLE
Snyk

### ISSUE THREAD

**Issue by modem7** [omegion/ssh-manager#16]
One last recommendation (honest!......probably!) for automated code coverage/security/pull requests that might be useful, would be Snyk. 

https://app.snyk.io/

If you aren't already aware of Snyk, it allows you to get notified about and potentially remediate security issues within your repos. 

It's a good/easy way of dealing with multiple repos and code bases from a single location, and seeing what is causing the issues.

![image](https://user-images.githubusercontent.com/4349962/147626597-b4007759-10a6-406c-bccf-30b8f0417273.png)

![image](https://user-images.githubusercontent.com/4349962/147626699-3c7df84c-288b-4c59-ad2a-4f1ebeb64688.png)

Please close this at your discretion.

**Comment by omegion** [comment]
Hey, I was not aware of Snyk before. I will set up integration right away, it seems super useful. Thanks for the suggestion again :)

**Comment by omegion** [comment]
https://github.com/omegion/ssh-manager/pull/17
Setup is done, thnx again.
