### ISSUE TITLE
[Feature Request] - Add Windows binary to packages

### ISSUE THREAD

**Issue by modem7** [omegion/ssh-manager#22]
Would it be possible to add the Windows binary to the releases as well as Linux + OS X?

Hopefully something like `windows/amd64` would suffice according to [0-go-os-arch.md](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63) and `go tool dist list`

**Comment by modem7** [comment]
If this is done, I've also taken the liberty to update the readme to reflect how users might be able to download natively with Powershell in https://github.com/omegion/ssh-manager/pull/23

**Comment by omegion** [comment]
Good call! I will test to build for `windows` and try to test it. I will create a PR for it soon.
