### ISSUE TITLE
Prebuilt binaries weren't released in GitHub Releases

### ISSUE THREAD

**Issue by suzuki-shunsuke** [omegion/ssh-manager#239]
Prebuilt binaries weren't released at [v1.3.0](https://github.com/omegion/ssh-manager/releases/tag/v1.3.0) and [v1.3.1](https://github.com/omegion/ssh-manager/releases/tag/v1.3.1).

<img width="310" alt="image" src="https://github.com/omegion/ssh-manager/assets/13323303/45a942ab-a6dc-44ed-95c3-d5b0dfe18b64">

~~It seems that the release step was removed.~~

- https://github.com/omegion/ssh-manager/compare/v1.2.0...v1.3.0
- https://github.com/omegion/ssh-manager/commit/f7b2ef42782f01832dcd51a3e8385334ce5ead5f

Could you release prebuilt binaries in GitHub Releases?

**Comment by omegion** [comment]
It is fixed now: https://github.com/omegion/ssh-manager/commit/96a3a9e868c7c2ceaffc80980e90da6bd15f7ced

**Comment by suzuki-shunsuke** [comment]
Thank you!
