### ISSUE TITLE
'go get' in module mode is deprecated

### ISSUE THREAD

**Issue by deividaspetraitis** [omegion/ssh-manager#28]
**Describe the bug**
Unable to install ssh-manager

**To Reproduce**

 ```
go get -u github.com/omegion/ssh-manager
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Expected behavior**
I expect to build `ssh-manager` localy as per [README](https://github.com/omegion/ssh-manager#installation)

**Environment:**
* CLI Version (retrieve with `ssh-manager version`):
* Operating System/Architecture: Arch Linux

**Comment by omegion** [comment]
Thanks for the feedback @deividaspetraitis. I created a PR to use `go install ...` command instead. Alternatively, you can directly download binaries for your environment. You can find the instructions in README.
