### ISSUE TITLE
Stopped working with bitwarden

### ISSUE THREAD

**Issue by e11bits** [omegion/ssh-manager#61]
**Describe the bug**
Does not seem to work any more with bitwarden in any way

**To Reproduce**
1. `bw login --check`
2. "You` are logged in!"
3. `ssh-manager list --provider bw`
4. "Error: unexpected end of JSON input"

**Expected behavior**
Show list of ssh keys saved in bitwarden

**Environment:**
* CLI Version (retrieve with `ssh-manager version`): v0.16.0 
* Operating System/Architecture: Linux 5.15.0-25-generic #25-Ubuntu SMP x86_64

**Additional context**
go version go1.18.1 linux/amd64
bw version 1.22.0
Ubuntu 22.04 LTS

**Comment by e11bits** [comment]
`DEBU[22-04-2022 17:43:36] Syncing Bitwarden Vault.`                     
`DEBU[22-04-2022 17:43:36] Getting items in Bitwarden.         `         
`Error: unexpected end of JSON input`

**Comment by e11bits** [comment]
After logout/login/unlock with bw it works fine again.

**Comment by omegion** [comment]
I am glad the issue is solved. We can add more visibility for Bitwarden. Probably it was failing to fetch the item. But the logging did not show it. I will create a ticket to add more visibility.

**Comment by omegion** [comment]
https://github.com/omegion/ssh-manager/issues/62
