### ISSUE TITLE
Error when trying to save with 1password

### ISSUE THREAD

**Issue by SmutsMuts** [omegion/ssh-manager#8]
**Environment:**
`INFO[03-11-2021 13:48:01] ssh-manager 0.0.0`

* CLI Version: 1.12.3 ([1password](https://app-updates.agilebits.com/product_history/CLI))
* Operating System/Architecture: Windows 11

**Expected Behavior:**
Saving the ssh files to 1password

**Actual Behavior:**
Getting this error: `Error: 'op create': Execution failed:`

**Steps to Reproduce:**
installed go
ran `go get -u github.com/omegion/ssh-manager`
started the ssh-agent service
ran the following command:
`ssh-manager add --name new-ssh-key --private-key C:\Users\username\.ssh\id_rsa --public-key C:\Users\username\.ssh\id_rsa.pub --provider op`

**Comment by omegion** [comment]
@SmutsMuts Can you please run the command again with `--logLevel` flag? It seems `op` command fails but we cannot see the error.
